# ???????????
logging.level.org.zalando.logbook=TRACE
logging.level.ru.yandex.practicum.filmorate=DEBUG

# ???? ?????? H2
spring.datasource.url=jdbc:h2:mem:filmoratedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ????????????? ?????
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# ??????? H2 (??? ???????)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console