# ===================== ??????????? =====================
logging.level.org.springframework.jdbc=DEBUG
logging.level.ru.yandex.practicum.filmorate=DEBUG
logging.level.org.zalando.logbook=TRACE

# ===================== ???? ?????? =====================
# ??????? ????? ? ?????? ??????????? ? ???? ./db/filmorate
spring.datasource.url=jdbc:h2:file:./db/filmorate;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# ????????????? ????????? schema.sql ??? ?????? ??????????
spring.sql.init.mode=always

# H2 Console ??? ??????? ???????? ??????
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console