-- Сброс таблиц (для удобства разработки)
DROP TABLE IF EXISTS film_likes;
DROP TABLE IF EXISTS film_genres;
DROP TABLE IF EXISTS friendships;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS mpa_ratings;
DROP TABLE IF EXISTS genres;

-- Справочник рейтингов MPA
CREATE TABLE IF NOT EXISTS mpa_ratings (
                                           id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           name VARCHAR(10) NOT NULL,
    description VARCHAR(200)
    );

-- Справочник жанров
CREATE TABLE IF NOT EXISTS genres (
                                      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      name VARCHAR(50) NOT NULL
    );

-- Пользователи
CREATE TABLE IF NOT EXISTS users (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email VARCHAR(255) NOT NULL UNIQUE,
    login VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    birthday DATE NOT NULL
    );

-- Фильмы
CREATE TABLE IF NOT EXISTS films (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(255) NOT NULL,
    description VARCHAR(200),
    release_date DATE NOT NULL,
    duration INTEGER NOT NULL CHECK (duration > 0),
    mpa_rating_id INTEGER REFERENCES mpa_ratings(id)
    );

-- Связь фильм-жанр (многие-ко-многим)
CREATE TABLE IF NOT EXISTS film_genres (
                                           film_id INTEGER REFERENCES films(id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genres(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
    );

-- Лайки
CREATE TABLE IF NOT EXISTS film_likes (
                                          film_id INTEGER REFERENCES films(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
    );

-- Дружба
CREATE TABLE IF NOT EXISTS friendships (
                                           user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    friend_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('CONFIRMED', 'UNCONFIRMED')),
    PRIMARY KEY (user_id, friend_id)
    );

-- Добавляем базовые данные
INSERT INTO mpa_ratings (name, description) VALUES
                                                ('G', 'У фильма нет возрастных ограничений'),
                                                ('PG', 'Детям рекомендуется смотреть с родителями'),
                                                ('PG-13', 'Детям до 13 лет просмотр не желателен'),
                                                ('R', 'Лицам до 17 лет просмотр только с родителем'),
                                                ('NC-17', 'Лицам до 18 лет просмотр запрещён');

INSERT INTO genres (name) VALUES
                              ('Комедия'),
                              ('Драма'),
                              ('Мультфильм'),
                              ('Триллер'),
                              ('Документальный'),
                              ('Боевик');